# Generated by Django 3.1.3 on 2020-11-28 09:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_num', models.CharField(max_length=3)),
                ('code_prev_num', models.IntegerField(default='0912')),
            ],
            options={
                'ordering': ['code_num'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Inviter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_hired', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_of_fired', models.DateTimeField(blank=True, null=True)),
                ('is_fired', models.BooleanField(default=False)),
                ('phone_num', models.CharField(max_length=11)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inviters.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonthOf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.IntegerField()),
                ('month_name', models.CharField(default='فروردین', max_length=20)),
            ],
            options={
                'ordering': ['month_number'],
            },
        ),
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeks_of', models.IntegerField()),
                ('year_of', models.IntegerField(default=1400)),
                ('price_of_sell', models.CharField(max_length=30)),
                ('extra_detail', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inviters.company')),
                ('inviters', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inviters.inviters')),
                ('monthof', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inviters.monthof')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('amount', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('inviters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inviters.inviters')),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('amount', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('inviters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inviters.inviters')),
            ],
        ),
        migrations.CreateModel(
            name='HourlyOffTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('inviters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inviters.inviters')),
            ],
        ),
        migrations.CreateModel(
            name='DailyOffTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('inviters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inviters.inviters')),
            ],
        ),
        migrations.CreateModel(
            name='CodeUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_use', models.IntegerField(default=1399, max_length=4)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inviters.code')),
                ('inviters', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inviters.inviters')),
                ('monthof', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inviters.monthof')),
            ],
        ),
    ]
