# Generated by Django 3.1.3 on 2020-11-28 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inviters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1400, max_length=4)),
                ('day', models.IntegerField(default=15, max_length=2)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inviters.company')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inviters.monthof')),
            ],
        ),
    ]
