# Generated by Django 3.1.3 on 2020-11-28 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inviters', '0002_seminar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sells',
            name='monthof',
        ),
        migrations.RemoveField(
            model_name='sells',
            name='weeks_of',
        ),
        migrations.RemoveField(
            model_name='sells',
            name='year_of',
        ),
        migrations.AddField(
            model_name='codeusage',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inviters.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inviters',
            name='date_of_end_esurance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inviters',
            name='date_of_start_esurance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sells',
            name='seminar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inviters.seminar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codeusage',
            name='year_of_use',
            field=models.IntegerField(default=1400),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='day',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='year',
            field=models.IntegerField(default=1400),
        ),
    ]
