# Generated by Django 3.1.3 on 2020-11-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inviters', '0003_auto_20201128_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sells',
            name='company',
        ),
    ]
