# Generated by Django 3.1.3 on 2020-11-28 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inviters', '0005_seminar_is_vebinar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=300)),
                ('card_price', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Sells',
            new_name='TahatorSells',
        ),
        migrations.CreateModel(
            name='HotelSaziSells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_detail', models.TextField(blank=True, null=True)),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inviters.cardstype')),
                ('inviters', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inviters.inviters')),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inviters.seminar')),
            ],
        ),
    ]
