# Generated by Django 3.1.3 on 2020-12-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inviters', '0007_auto_20201128_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='code_name',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
    ]
