# Generated by Django 3.1.3 on 2020-11-06 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(max_length=11)),
                ('added_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.CharField(default='Hamed', max_length=50)),
                ('invited_by', models.CharField(default='Maede', max_length=50)),
                ('for_date', models.CharField(blank=True, default='NA', max_length=11)),
                ('for_time', models.CharField(blank=True, default='NA', max_length=11)),
                ('is_present', models.BooleanField(default=False)),
                ('is_purchased', models.BooleanField(default=False)),
                ('user_firstname', models.CharField(blank=True, default='NA', max_length=100)),
                ('user_lastname', models.CharField(blank=True, default='NA', max_length=200)),
                ('user_address', models.CharField(blank=True, default='NA', max_length=800)),
                ('national_code', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
