# Generated by Django 3.1.3 on 2020-11-08 20:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('date_of_hired', models.DateField()),
                ('date_of_fired', models.DateField()),
                ('phone_num', models.IntegerField()),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_num', models.IntegerField()),
                ('code_prev_num', models.IntegerField(default='0912')),
            ],
            options={
                'ordering': ['code_num'],
            },
        ),
        migrations.CreateModel(
            name='Inviter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('date_of_hired', models.DateField()),
                ('date_of_fired', models.DateField()),
                ('phone_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seminar_name', models.TextField()),
                ('seminar_date', models.DateField()),
            ],
            options={
                'ordering': ['seminar_name'],
            },
        ),
        migrations.CreateModel(
            name='Sans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sans', models.TextField()),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.seminar')),
            ],
            options={
                'ordering': ['sans'],
            },
        ),
        migrations.CreateModel(
            name='Invited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.IntegerField()),
                ('full_name', models.TextField()),
                ('added_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.adder')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.inviter')),
                ('sans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.sans')),
            ],
            options={
                'ordering': ['added_datetime'],
            },
        ),
        migrations.CreateModel(
            name='CodeUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_month', models.TextField()),
                ('date_year', models.TextField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.code')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.inviter')),
            ],
        ),
    ]
