# Generated by Django 3.1.3 on 2020-11-13 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeusage',
            name='date_month',
        ),
        migrations.RemoveField(
            model_name='codeusage',
            name='date_year',
        ),
        migrations.AddField(
            model_name='codeusage',
            name='date_of_use',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='seminar',
            name='seminar_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adder',
            name='date_of_fired',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='adder',
            name='date_of_hired',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='adder',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adder',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invited',
            name='full_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='inviter',
            name='date_of_fired',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='inviter',
            name='date_of_hired',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inviter',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inviter',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sans',
            name='sans',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='seminar_name',
            field=models.CharField(max_length=300),
        ),
    ]
