# Generated by Django 3.1.3 on 2020-11-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20201113_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adder',
            name='phone_num',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='inviter',
            name='phone_num',
            field=models.CharField(max_length=11),
        ),
    ]
