# Generated by Django 3.1.3 on 2020-11-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20201113_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adder',
            name='date_of_fired',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inviter',
            name='date_of_fired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
