# Generated by Django 3.1.3 on 2020-11-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20201113_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code_num',
            field=models.CharField(max_length=3),
        ),
    ]
