# Generated by Django 3.1.3 on 2020-11-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20201113_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthOf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.IntegerField()),
                ('month_name', models.CharField(default='فروردین', max_length=20)),
            ],
            options={
                'ordering': ['month_name'],
            },
        ),
        migrations.RemoveField(
            model_name='codeusage',
            name='date_of_use',
        ),
        migrations.AddField(
            model_name='codeusage',
            name='year_of_use',
            field=models.CharField(default=1399, max_length=4),
        ),
    ]
