# Generated by Django 3.1.3 on 2020-11-13 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20201113_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeusage',
            name='months',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='customers.monthof'),
            preserve_default=False,
        ),
    ]
