# Generated by Django 3.1.3 on 2020-11-13 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_codeusage_months'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeusage',
            old_name='months',
            new_name='monthof',
        ),
    ]
