# Generated by Django 3.1.3 on 2020-11-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20201110_1558'),
        ('customers', '0009_auto_20201113_1134'),
    ]

    operations = [
    ]
