# Generated by Django 3.1.3 on 2020-11-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_merge_20201114_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthof',
            options={'ordering': ['month_number']},
        ),
        migrations.AlterField(
            model_name='seminar',
            name='seminar_date',
            field=models.DateField(),
        ),
    ]
