# Generated by Django 3.1.3 on 2020-11-25 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_auto_20201114_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='HourlyOffTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeks_of', models.IntegerField()),
                ('year_of', models.IntegerField()),
                ('price_of_sell', models.CharField(max_length=30)),
                ('extra_detail', models.TextField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.company')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.inviter')),
                ('monthof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.monthof')),
            ],
        ),
        migrations.RemoveField(
            model_name='invited',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='invited',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='invited',
            name='sans',
        ),
        migrations.RemoveField(
            model_name='sans',
            name='seminar',
        ),
        migrations.DeleteModel(
            name='Adder',
        ),
        migrations.DeleteModel(
            name='Invited',
        ),
        migrations.DeleteModel(
            name='Sans',
        ),
        migrations.DeleteModel(
            name='Seminar',
        ),
    ]
