# Generated by Django 3.1.3 on 2020-11-25 12:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_auto_20201125_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyofftime',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourlyofftime',
            name='inviter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='customers.inviter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hourlyofftime',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('amount', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.inviter')),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('amount', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.inviter')),
            ],
        ),
        migrations.CreateModel(
            name='DailyOffTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField()),
                ('description', models.TextField(null=True)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.inviter')),
            ],
        ),
    ]
