# Generated by Django 3.1.3 on 2020-11-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_auto_20201125_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inviter',
            name='date_of_fired',
        ),
    ]
