# Generated by Django 3.1.3 on 2020-11-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_remove_inviter_date_of_fired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sells',
            name='year_of',
            field=models.IntegerField(default=1400),
        ),
    ]
