# Generated by Django 3.1.3 on 2020-11-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_auto_20201125_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sells',
            name='extra_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
