# Generated by Django 3.1.3 on 2020-11-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_auto_20201125_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyofftime',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
